### PR TITLE
Fixes #162: Add support for updating avatars for Users and Contacts/Leads

### LINKED ISSUE #162: Set avatar
## Version info
  - intercom-java version: 2.2.11
  - Java version: 1.8.0_131

## Expected behavior
Ability to set avatar

## Actual behavior
There is no setter method in the User object for the avatar. 
Is this by design?

### PR DESCRIPTION
**Pull request by thewheat**
Addresses https://github.com/intercom/intercom-java/issues/162 for setting avatar on the user record.

Added feature to contacts/leads as well as tested in REST API and it is supported for them as well

### CODE REVIEW

**Comment by choran** [comment]
@thewheat I know we are missing some testing for other parts of the user resource in Java but there is some testing that we could use for this feature. e.g. [here](https://github.com/intercom/intercom-java/blob/7449ccd00d58c18e3aa1544326e161d04163cf4b/intercom-java/src/test/java/io/intercom/api/UserTest.java#L167)
Think we can add the avatar attribute here so we could have a test for it? 
Does that make sense?

**Comment by thewheat** [comment]
@choran Got it 👍  Will add as soon as possible 😄

**Comment by choran** [comment]
Cool, I have merged in the other PRs but I can hold off on a release until you get this one updated.
That way we can release the three together
Cheers 👍

**Comment by thewheat** [comment]
@choran Tests added 👍

**Pull request merged**
